name: CI

on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: dotnet build FNA.Core
      run: |
        dotnet build -c Debug FNA.Core.csproj
        dotnet build -c Release FNA.Core.csproj
